// export const GET_ERRORS = 'GET_ERRORS'
export const GET_LOGIN_ERRORS = 'GET_LOGIN_ERRORS'
export const GET_REGISTER_ERRORS = 'GET_REGISTER_ERRORS'
export const SET_CURRENT_USER = 'SET_CURRENT_USER'